name: CI

on: [push, pull_request]

env:
  CC: clang
  CXX: clang++
  MIX_ENV: test
  WARNINGS_AS_ERRORS: true

jobs:
  test:
    name: Test (${{ matrix.label }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - label: OTP 29 compile
            elixir: 1.20.0-rc.4
            otp: 29.0-rc3
            rebar3: 3.27.0
            runtime_tests: false

          - label: OTP 28
            elixir: 1.19.4
            otp: 28.3
            rebar3: 3.25.1
            lint: true
            runtime_tests: true

    steps:
      - uses: actions/checkout@v5

      - name: Setup Beam
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
          rebar3-version: ${{ matrix.rebar3 }}
          version-type: strict
          install-hex: ${{ matrix.runtime_tests }}
          install-rebar: ${{ matrix.runtime_tests }}

      # - name: (Erlang) Check Formatting
      #   if: ${{ matrix.lint }}
      #   run: |
      #     clang-format --version
      #     make lint-format

      - name: (Erlang) eqWAlizer
        if: ${{ matrix.lint }}
        run: make lint-eqwalizer

      - name: (Erlang) Dialyzer
        if: ${{ matrix.lint }}
        run: make lint-dialyzer

      - name: (Erlang) Xref
        if: ${{ matrix.lint }}
        run: make lint-xref

      - name: (Erlang) Compile
        if: ${{ !matrix.runtime_tests }}
        run: rebar3 as test compile

      - name: (Erlang) Tests
        if: ${{ matrix.runtime_tests }}
        run: |
          rebar3 ct

      - name: (Elixir) Retrieve Mix Dependencies Cache
        if: ${{ matrix.runtime_tests }}
        uses: actions/cache@v4
        id: mix-cache
        with:
          path: deps
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - name: (Elixir) Install Mix Dependencies
        if: ${{ matrix.runtime_tests && steps.mix-cache.outputs.cache-hit != 'true' }}
        run: |
          mix deps.get

      - name: (Elixir) Check Formatting
        if: ${{ matrix.lint }}
        run: mix format --check-formatted

      - name: (Elixir) Tests
        if: ${{ matrix.runtime_tests }}
        run: mix test --trace

      - name: Logs
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: ct-logs-${{ matrix.otp }}-${{ matrix.elixir }}
          path: _build/test/logs/
